### ISSUE TITLE
SingleInstance WinForms Contribution

### ISSUE THREAD

**Issue by paul1956** [AutoItConsulting/examples-csharp#1]
In WinForms 5.0 SingleInstance is being added but the current implementation (for VB) will not work. It seems you have solved all the issues in your sample. I was wondering if you would like to contribute your implementation? If you can't or don't want to do the work, but are OK with the use of your code can you provide an open source MIT license on your code that would allow it to be used (with credit) and I will pick it up. It will be ported to VB since the current file it sits in is all VB and that is what is driving the need but the code will be usable by any language. If you want to contribute and stay in C# that could also work.

**Comment by jonathanbennett73** [comment]
Hi. You are welcome to use the code. I just checked and it's already got an MIT license tagged on the repo and at the top of the source files and LICENSE file in the root. Let me know if there's something specific you need that I've not already done.

**Comment by paul1956** [comment]
Could you post this message https://github.com/dotnet/winforms/issues/2056, I used just a few lines from namedPipe Client and Server mostly the concert of the XML code. The Root License says I would need to include the License file and don't think that is allowed. The code is open source and also under the MIT license.
